// Mocks generated by Mockito 5.3.2 from annotations
// in netflix_clone/test/features/new_&_hot/presentation/bloc/new_and_hot_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:netflix_clone/core/errors/failures.dart' as _i5;
import 'package:netflix_clone/features/new_&_hot/domain/entities/coming_soon.dart'
    as _i6;
import 'package:netflix_clone/features/new_&_hot/domain/entities/everyones_watching.dart'
    as _i8;
import 'package:netflix_clone/features/new_&_hot/domain/usecases/get_coming_soon.dart'
    as _i3;
import 'package:netflix_clone/features/new_&_hot/domain/usecases/get_everyones_watching.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetComingSoon].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetComingSoon extends _i1.Mock implements _i3.GetComingSoon {
  MockGetComingSoon() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.ComingSoon>> call(
          _i3.Params? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.ComingSoon>>.value(
            _FakeEither_0<_i5.Failure, _i6.ComingSoon>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.ComingSoon>>);
}

/// A class which mocks [GetEveryOnesWatching].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetEveryOnesWatching extends _i1.Mock
    implements _i7.GetEveryOnesWatching {
  MockGetEveryOnesWatching() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i8.EveryOnesWatching>> call(
          _i7.Params? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i8.EveryOnesWatching>>.value(
                _FakeEither_0<_i5.Failure, _i8.EveryOnesWatching>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i8.EveryOnesWatching>>);
}
