name: netflix_clone
description: A  Netflix clone app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^3.0.1
  get: ^4.6.5
  video_player: ^2.4.7
  bordered_text: ^2.0.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  injectable: ^1.5.3
  json_annotation: ^4.7.0
  http: ^0.13.5
  flutter_bloc: ^8.1.1
  share_plus: ^6.0.1

dev_dependencies:
  build_runner: ^2.3.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.2.0
  injectable_generator: ^1.5.4
  json_serializable: ^6.5.3
  mockito: ^5.3.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
