// Mocks generated by Mockito 5.3.2 from annotations
// in netflix_clone/test/features/home/data/repository/home_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:netflix_clone/features/home/data/datasources/get_released_in_past_year_data.dart'
    as _i3;
import 'package:netflix_clone/features/home/data/datasources/get_south_indian_cinema_data.dart'
    as _i5;
import 'package:netflix_clone/features/home/data/datasources/get_tense_dramas_data.dart'
    as _i6;
import 'package:netflix_clone/features/home/data/datasources/get_top_10_data.dart'
    as _i7;
import 'package:netflix_clone/features/home/data/datasources/get_trending_now_data.dart'
    as _i8;
import 'package:netflix_clone/features/home/data/models/home_dto.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeHomeDto_0 extends _i1.SmartFake implements _i2.HomeDto {
  _FakeHomeDto_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetReleasedInPastYearData].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetReleasedInPastYearData extends _i1.Mock
    implements _i3.GetReleasedInPastYearData {
  MockGetReleasedInPastYearData() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.HomeDto> getData() => (super.noSuchMethod(
        Invocation.method(
          #getData,
          [],
        ),
        returnValue: _i4.Future<_i2.HomeDto>.value(_FakeHomeDto_0(
          this,
          Invocation.method(
            #getData,
            [],
          ),
        )),
      ) as _i4.Future<_i2.HomeDto>);
}

/// A class which mocks [GetSouthIndianCinemaData].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetSouthIndianCinemaData extends _i1.Mock
    implements _i5.GetSouthIndianCinemaData {
  MockGetSouthIndianCinemaData() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.HomeDto> getData() => (super.noSuchMethod(
        Invocation.method(
          #getData,
          [],
        ),
        returnValue: _i4.Future<_i2.HomeDto>.value(_FakeHomeDto_0(
          this,
          Invocation.method(
            #getData,
            [],
          ),
        )),
      ) as _i4.Future<_i2.HomeDto>);
}

/// A class which mocks [GetTenseDramaData].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTenseDramaData extends _i1.Mock implements _i6.GetTenseDramaData {
  MockGetTenseDramaData() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.HomeDto> getData() => (super.noSuchMethod(
        Invocation.method(
          #getData,
          [],
        ),
        returnValue: _i4.Future<_i2.HomeDto>.value(_FakeHomeDto_0(
          this,
          Invocation.method(
            #getData,
            [],
          ),
        )),
      ) as _i4.Future<_i2.HomeDto>);
}

/// A class which mocks [GetTop10Data].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTop10Data extends _i1.Mock implements _i7.GetTop10Data {
  MockGetTop10Data() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.HomeDto> getData() => (super.noSuchMethod(
        Invocation.method(
          #getData,
          [],
        ),
        returnValue: _i4.Future<_i2.HomeDto>.value(_FakeHomeDto_0(
          this,
          Invocation.method(
            #getData,
            [],
          ),
        )),
      ) as _i4.Future<_i2.HomeDto>);
}

/// A class which mocks [GetTrendingNowData].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTrendingNowData extends _i1.Mock
    implements _i8.GetTrendingNowData {
  MockGetTrendingNowData() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.HomeDto> getData() => (super.noSuchMethod(
        Invocation.method(
          #getData,
          [],
        ),
        returnValue: _i4.Future<_i2.HomeDto>.value(_FakeHomeDto_0(
          this,
          Invocation.method(
            #getData,
            [],
          ),
        )),
      ) as _i4.Future<_i2.HomeDto>);
}
