// Mocks generated by Mockito 5.3.2 from annotations
// in netflix_clone/test/features/home/presentation/bloc/home_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:netflix_clone/core/errors/failures.dart' as _i5;
import 'package:netflix_clone/core/usecases/usecase.dart' as _i7;
import 'package:netflix_clone/features/home/domain/entities/home.dart' as _i6;
import 'package:netflix_clone/features/home/domain/usecases/get_released_in_past_year.dart'
    as _i3;
import 'package:netflix_clone/features/home/domain/usecases/get_south_indian_cinema.dart'
    as _i8;
import 'package:netflix_clone/features/home/domain/usecases/get_tense_dramas.dart'
    as _i9;
import 'package:netflix_clone/features/home/domain/usecases/get_top_10.dart'
    as _i10;
import 'package:netflix_clone/features/home/domain/usecases/get_trending_now.dart'
    as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetReleasedInPastYear].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetReleasedInPastYear extends _i1.Mock
    implements _i3.GetReleasedInPastYear {
  MockGetReleasedInPastYear() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Home>> call(_i7.NoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Home>>.value(
            _FakeEither_0<_i5.Failure, _i6.Home>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Home>>);
}

/// A class which mocks [GetSouthIndianCinema].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetSouthIndianCinema extends _i1.Mock
    implements _i8.GetSouthIndianCinema {
  MockGetSouthIndianCinema() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Home>> call(_i7.NoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Home>>.value(
            _FakeEither_0<_i5.Failure, _i6.Home>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Home>>);
}

/// A class which mocks [GetTenseDrama].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTenseDrama extends _i1.Mock implements _i9.GetTenseDrama {
  MockGetTenseDrama() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Home>> call(_i7.NoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Home>>.value(
            _FakeEither_0<_i5.Failure, _i6.Home>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Home>>);
}

/// A class which mocks [GetTop10].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTop10 extends _i1.Mock implements _i10.GetTop10 {
  MockGetTop10() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Home>> call(_i7.NoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Home>>.value(
            _FakeEither_0<_i5.Failure, _i6.Home>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Home>>);
}

/// A class which mocks [GetTrendingNow].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTrendingNow extends _i1.Mock implements _i11.GetTrendingNow {
  MockGetTrendingNow() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Home>> call(_i7.NoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Home>>.value(
            _FakeEither_0<_i5.Failure, _i6.Home>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Home>>);
}
