// Mocks generated by Mockito 5.3.2 from annotations
// in netflix_clone/test/features/search/presentation/bloc/search_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:netflix_clone/core/errors/failures.dart' as _i5;
import 'package:netflix_clone/core/usecases/usecase.dart' as _i7;
import 'package:netflix_clone/features/search/domain/entities/search_active_model.dart'
    as _i9;
import 'package:netflix_clone/features/search/domain/entities/search_idle_model.dart'
    as _i6;
import 'package:netflix_clone/features/search/domain/usecases/get_search_idle_data.dart'
    as _i3;
import 'package:netflix_clone/features/search/domain/usecases/get_search_results.dart'
    as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetSearchIdleData].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetSearchIdleData extends _i1.Mock implements _i3.GetSearchIdleData {
  MockGetSearchIdleData() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.SearchIdleModel>> call(
          _i7.NoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.SearchIdleModel>>.value(
                _FakeEither_0<_i5.Failure, _i6.SearchIdleModel>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.SearchIdleModel>>);
}

/// A class which mocks [GetSearchResults].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetSearchResults extends _i1.Mock implements _i8.GetSearchResults {
  MockGetSearchResults() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i9.SearchActiveModel>> call(
          _i8.Params? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i9.SearchActiveModel>>.value(
                _FakeEither_0<_i5.Failure, _i9.SearchActiveModel>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i9.SearchActiveModel>>);
}
